### ISSUE TITLE
Configuration for rule "no-underscore-dangle" is invalid: Value "data["1"].allowAfterThis"

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/eslint-config-trails#11]
Error: eslint-config-trails/rules/style: Configuration for rule "no-underscore-dangle" is invalid: Value "data["1"].allowAfterThis" has additional properties.

Referenced from: trails Referenced from: /Volumes/Repos/Coding/OpenSource/trails/trailpack-swagger/package.json

**Comment by troy0820** [comment]
This happens to me when I try to run npm test in trails repo as well.

**Comment by tjwebb** [comment]
err, I wonder why I don't see this locally. I'll investigate.

**Comment by tjwebb** [comment]
@troy0820 @konstantinzolotarev this should be resolved. This happens when eslint 1.x is used instead of 2.x
