### ISSUE TITLE
Eslint v2.0.0 paserOptions

### ISSUE THREAD

**Issue by troy0820** [trailsjs/eslint-config-trails#13]
In the docs for ESLINT 2.0.0 it states using `parserOptions` and `ecmaVerion: 6` inside that object along with emcaFeatures flags.  

I can make a PR if we wish to implement that.

**Comment by tjwebb** [comment]
@troy0820 can you elaborate? I think you know more about eslint than I do

**Comment by troy0820** [comment]
<img width="1171" alt="screen shot 2016-04-14 at 2 01 00 pm" src="https://cloud.githubusercontent.com/assets/5985850/14538425/ba5fbdd6-0249-11e6-962e-1019fee08d15.png">

If you are migrating from `eslint@1.0.0 to`eslint@2.0.0`, you are going to have to place the`ecmaFeatures`object inside`parserOptions` per the docs.  

Also, you can put the flags that you are using inside of `ecmaFeatures` like this or what airbnb does.

<img width="1192" alt="screen shot 2016-04-14 at 2 05 19 pm" src="https://cloud.githubusercontent.com/assets/5985850/14538811/969da46a-024b-11e6-9490-1edabfc69bb3.png">

**Comment by tjwebb** [comment]
@troy0820 can you submit a PR?

EDIT: looks like @Alaneor beat you to it :)
