### ISSUE TITLE
 no-global-assign issue

### ISSUE THREAD

**Issue by konstantinzolotarev** [trailsjs/eslint-config-trails#17]
After clean installation new issue appears:
`1:1  error  Definition for rule 'no-global-assign' was not found  no-global-assign`

Also all PRs in main repo affected

**Comment by tjwebb** [comment]
I need to upgrade everything to eslint 3. eslint 2.x must have introduced an incompatibility. 

I hate semver sometimes.

**Comment by wbprice** [comment]
`no-global-assign` was introduced in `ESLint 3.3.0`.  I'll take a look at updating the `estlint` dependency version to fix this.

**Comment by tjwebb** [comment]
Now eslint is on v4, so testing against that.
