### ISSUE TITLE
Airbnb rules

### ISSUE THREAD

**Issue by clayrisser** [trailsjs/eslint-config-trails#18]
Currently, Trails is using its own set of rules for styling. I think it would be better to use a standard that's had widespread adoption, rather than just a random personal preference. I would suggest the airbnb eslint rules as it has the most widespread adoption.

https://github.com/airbnb/javascript

**Comment by konstantinzolotarev** [comment]
@jamrizzi You could easily change your eslint settings in your project. And fix all problems using 
`eslint --fix`.

**Comment by clayrisser** [comment]
You're missing the point of the issue. I know I can change the rules in my project. I've already done that. TrailsJS is not using widespread adopted style guidelines which affect many things beyond making me swap out the linting rules. It affects things like the yeoman generators, and the styling recommended for trailpacks (because you should follow the Trails style guidelines when making a trailpack)

**Comment by tjwebb** [comment]
Choosing styling from airbnb instead of spotify or npm is also a "random personal preference". Lots of companies, groups, people, and frameworks publish their own styles. At the end of the day, you just pick a style that matches your chosen framework/ecosystem and go with it. It's much more important that we simply pick a style and be consistent within the ecosystem than which *particular* style we choose. We've already chosen one, and changing it will just make all of our existing code and trailpacks incompatible with it. This creates more work for everyone, not less.

**Comment by tjwebb** [comment]
If you want everyone to follow exactly the same style across all js projects everywhere, submit this issue to eslint and suggest that they remove all configuration options and just force everyone on earth to use your specific, preferred style.

**Comment by clayrisser** [comment]
I agree, choosing a style from airbnb is a personal preference, so it doesn't have to be from airbnb (airbnb just happens to be the most used). It could be from spoitify or npm. I just think that maybe it would be nice to use a style that already has a community around it.

I don't believe eslint should force a style because that's not the point of eslint. Eslint is about forcing consistency, not an opinion. I just think the opinion used by Trails should be an opinion that is already widely adopted.

**Comment by clayrisser** [comment]
I completely agree with everything you're saying in regards to the importance of this issue. I can't seem to find who's style you are following. It seems completely made up.

**Comment by tjwebb** [comment]
It's the standard eslint styles, plus rules that change according to which node version is currently supported (since features come and go with each node minor release: http://node.green/).

Also, all rules are made up. Welcome to earth.
