### ISSUE TITLE
allow different rules to be used for files inside of test/ vs. elsewhere

### ISSUE THREAD

**Issue by tjwebb** [trailsjs/eslint-config-trails#7]
I want to be able to console.log inside of test files, for example.

**Comment by wbprice** [comment]
ESlint should already allow the developer to override the global `.eslintrc` per directory. The behavior is described [in their docs](http://eslint.org/docs/user-guide/configuring.html#configuration-cascading-and-hierarchy).  Are you running into an edge case?

**Comment by tjwebb** [comment]
Yea it should work, it'd be nice if this were just done by default. e.g. in the generator. So this repo should have some separate rules for testing, and then the generator updated to put the eslintrc file in test/

**Comment by wbprice** [comment]
Cool. We're doing something pretty similar with React-specific rules already. In the generator's test folder, make an .eslintrc containing

```
{
  "extends": "trails/test"
}
```

and I'll do the honors on this side.
